steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'functions', 'deploy', 'ingest_posts',
        '--runtime=python311',
        '--trigger-http',
        '--allow-unauthenticated',
        '--entry-point=ingest_posts',
        '--region=us-central1',
        '--source=.',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
